title: Focso Lorengia
subtitle: “When you meet your Buddha, kill him”
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
email: your-email@domain.com
twitter_username: jekyllrb
github_username:  jekyll

favicon: assets/favicon.png

css:
    - https://fonts.googleapis.com/css?family=Merriweather|Oswald
    - css/main.css

js:
    early:
    late:
        - js/jquery.min.js
        - js/jquery.scrollme.min.js
        - js/stickUp.min.js
        - js/fchoue.js

markdown: kramdown

keywords: nope
description: nope

collections:
  conf:
  dida:
  misc:
  papers:
  refcards:

sass:
  style: compressed

exclude: [vendor, BACKUP, script, Gemfile, Gemfile.lock, .gitignore]
