# Information
title:               tetrapharmakon.github.io
author:
  name:              Fouche
  url:               http://people.sissa.it/~floregi/
  email:             tetrapharmakon@gmail.com

# Conversion
# markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "strikethrough", "smart"]

# Output
permalink: /epistolae/:title/

# Layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
